version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: productcatalog_postgres
    restart: always
    environment:
      POSTGRES_DB: ProductCatalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ProductCatalog.API/Dockerfile
    container_name: productcatalog_api
    depends_on:
      - postgres
      - minio
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=productcatalog;Username=postgres;Password=postgres
    ports:
      - "5000:8080"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: