name: CI - ProductCatalog

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Rodar testes
        run: dotnet test --no-build --configuration Release

      - name: Build imagem Docker
        run: docker build -t productcatalog-api .